[package]
name = "commandlines"
version = "0.0.2"
description = "A command line argument parsing library for Rust"
authors = ["Chris Simpkins <chris@sourcefoundry.org>"]
repository = "https://github.com/chrissimpkins/commandlines-rust"
readme = "README.md"
license = "MIT"

[dependencies]
